name: Add Wiki
on:
  workflow_dispatch:
jobs:
  add_wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Wiki
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -xe
          git config user.name  "[bot] ${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git submodule add https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.wiki.git wiki
          git add .gitmodules wiki
          git commit -m "docs: add GitHub wiki as submodule"
          git push
      - name: Create Glossary Document
        run: |
          set -xe
          cd wiki
          touch 用語集.md
          git add 用語集.md
          git commit -m "Update Wiki"
          git push
